version: '3'

services:
  car.bookingservice:
    image: carbookingservice 
    build:
      context: ./carbookingservice
      dockerfile: Dockerfile
    container_name: carbookingservice
    environment:
      - "RabbitMqHost=rabbit"
      - "RabbitMqUsername=guest"
      - "RabbitMqPassword=guest"
    depends_on:
      - rabbit

  flight.bookingservice:
    image: flightbookingservice
    build:
      context: ./flightbookingservice
      dockerfile: Dockerfile
    container_name: flightbookingservice
    environment:
      - "RabbitMqHost=rabbit"
      - "RabbitMqUsername=guest"
      - "RabbitMqPassword=guest"
    depends_on:
      - rabbit

  hotel.bookingservice:
    image: hotelbookingservice 
    build:
      context: ./hotelbookingservice
      dockerfile: Dockerfile
    container_name: hotelbookingservice
    environment:
      - "RabbitMqHost=rabbit"
      - "RabbitMqUsername=guest"
      - "RabbitMqPassword=guest"
    depends_on:
      - rabbit

  producer:
    image: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    environment:
      - "RabbitMqHost=rabbit"
      - "RabbitMqUsername=guest"
      - "RabbitMqPassword=guest"
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3.7.2-management
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"